#write  a program to cover all the string operations
text="Hello World"
print("Original:",text)
print("len:",len(text))
print("upper:",text.upper())
print("lower:",text.lower())
print("title:",text.title())
print("capitalize:",text.capitalize())
print("swapcase:",text.swapcase())
print("count l:",text.count('l'))
print("find World:",text.find('World'))
print("replace:",text.replace('World','Python'))
print("startswith H:",text.startswith('H'))
print("endswith d:",text.endswith('d'))
print("split:",text.split())
print("join:",'-'.join(text))
print("strip:","  Hello  ".strip())
print("index o:",text.index('o'))
print("isalpha:",text.isalpha())
print("isdigit:",text.isdigit())
print("isalnum:",text.isalnum())
print("islower:",text.islower())
print("isupper:",text.isupper())
print("istitle:",text.istitle())
print("center:",text.center(20,'*'))
print("ljust:",text.ljust(20,'-'))
print("rjust:",text.rjust(20,'-'))
print("encode:",text.encode())
print("expandtabs:","H\te\tl\tl\to".expandtabs(2))
print("partition:",text.partition(' '))
print("rpartition:",text.rpartition(' '))
print("zfill:",text.zfill(15))
