from decimal import Decimal,getcontext
print(Decimal(0.002)+Decimal(0.02))
print(Decimal(10.2)/Decimal(2.3))
def explore_decimal_functions():
    print("Context Management")
    current_context = getcontext()
    print(f"Default Context: {current_context}")
    new_context = Decimal.Context(prec=5, rounding=Decimal.ROUND_HALF_UP)
    Decimal.setcontext(new_context)
    print(f"New Context (prec=5, ROUND_HALF_UP): {Decimal.getcontext()}")
    with Decimal.localcontext() as ctx:
        ctx.prec = 3
        print(f"Local Context (prec=3): {Decimal.getcontext()}")
        num_local = Decimal.Decimal("1.2345")
        print(f"Number in local context: {num_local}")
    print(f"Back to previous context: {Decimal.getcontext()}")
    print("decimal number creations ")
    d_int = Decimal.Decimal(10)
    d_str = Decimal.Decimal("3.14159")
    d_float = Decimal.Decimal(0.1) 
    d_tuple = Decimal.Decimal((0, (1, 2, 3), -2)) 
    print(f"int: {d_int}")
    print(f"string: {d_str}")
    print(f"float: {d_float}")
    print(f"tuple: {d_tuple}")
    print(" arthamatic operators")
    a = Decimal.Decimal("10.5")
    b = Decimal.Decimal("3.2")
    print(f"{a} + {b} = {a + b}")
    print(f"{a} - {b} = {a - b}")
    print(f"{a} * {b} = {a * b}")
    print(f"{a} / {b} = {a / b}")
    print(f"{a} // {b} (floor division) = {a // b}")
    print(f"{a} % {b} (modulo) = {a % b}")
    print(f"{a} ** 2 (power) = {a ** 2}")
    print("mathematical functions")
    x = Decimal.Decimal("9.0")
    print(f"sqrt({x}) = {x.sqrt()}")
    print(f"exp(decimal.Decimal(1)) = {Decimal.Decimal(1).exp()}")
    print(f"ln(decimal.Decimal(10)) = {Decimal.Decimal(10).ln()}")
    print(f"log10(decimal.Decimal(100)) = {Decimal.Decimal(100).log10()}")
    print("\n--- Rounding and Quantization ---")
    num_to_round = Decimal.Decimal("123.4567")
    print(f"Original: {num_to_round}")
    print(f"Quantize to 2 decimal places: {num_to_round.quantize(Decimal.Decimal('0.00'))}")
    print(f"roundceiling: {num_to_round.quantize(Decimal.Decimal('0.00'), rounding=Decimal.ROUND_CEILING)}")
    print("\n--- Special Values and Comparisons ---")
    inf = Decimal.Decimal("Infinity")
    neg_inf = Decimal.Decimal("-Infinity")
    nan = Decimal.Decimal("NaN")
    print(f"Infinity: {inf}, -Infinity: {neg_inf}, None: {nan}")
    print(f"{a} > {b}: {a > b}")
    print(f"{a}.compare({b}): {a.compare(b)}") 
    print("methods")
    val = Decimal.Decimal("-15.75")
    print(f"Original: {val}")
    print(f"Absolute value: {val.copy_abs()}")
    print(f"Negate: {val.copy_negate()}")
    print(f"Sign: {val.sign()}") 
    print(f"Adjusted exponent: {val.adjusted()}")
    print(f"as_tuple(): {val.as_tuple()}")
if __name__ == "__main__":
    explore_decimal_functions()